# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "kubemaster"
    vb.memory = 8192
    vb.cpus = 4
  end

  config.vm.hostname = "kubemaster"
  config.vm.network "private_network", ip: "192.168.36.3"

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install -y vim wget
  SHELL

  config.vm.provision "shell", path: "setup-docker.sh"
  config.vm.provision "shell", path: "always-run.sh", run: "always"
end
