# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "kubemaster" do |node|
    node.vm.box = "centos/7"
    node.vm.box_check_update = false
    node.vm.network "private_network", ip: "172.28.128.10"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "kubemaster"
      vb.memory = 4096
      vb.cpus = 2
    end

    node.vm.provision "shell", inline: <<-SHELL
        yum update -y
        yum install -y vim wget
      SHELL
  
    node.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "kubenode01" do |node|
    node.vm.box = "centos/7"
    node.vm.box_check_update = false
    node.vm.network "private_network", ip: "172.28.128.11"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "kubenode01"
      vb.memory = 4096
      vb.cpus = 2
    end

    node.vm.provision "shell", inline: <<-SHELL
        yum update -y
        yum install -y vim wget
      SHELL
  
    node.vm.provision "shell", path: "bootstrap.sh"
  end
end
